name: Generate and upload docs

on:
  push:
    branches: master

jobs:
  ocaml:
    name: Slate docs
    runs-on: ubuntu-20.04
    env:
      package: "xapi-storage"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env
      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v0.2.8

      - name: Use ocaml
        uses: ocaml/setup-ocaml@v1
        with:
          ocaml-version: ${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repository: ${{ steps.dotenv.outputs.repository }}

      - name: Install dependencies
        run: |
          opam pin add . --no-action
          opam depext -u ${{ env.package }}
          opam install ${{ env.package }} --deps-only --with-doc -v
      - name: Docs
        run: |
          mkdir .gh-pages
          opam exec -- exec generator/src/main.exe -- gen_markdown --path=$DOCDIR
        env:
          DOCDIR: .gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .gh-pages
          publish_branch: slate
          destination_dir: source/includes/
          keep_files: false
